-- Aha!ve Supabase initial schema
-- Run this in Supabase SQL Editor or via Supabase CLI.
-- This migration is designed for the current frontend schema.

-- ─────────────────────────────────────────────────────────────
-- Enums
-- ─────────────────────────────────────────────────────────────

do $$
begin
  if not exists (select 1 from pg_type where typname = 'position') then
    create type public.position as enum ('DEV', 'DESIGN', 'PROMOTER', 'OTHER', 'NONE');
  end if;

  if not exists (select 1 from pg_type where typname = 'created_type') then
    create type public.created_type as enum ('INIT', 'SELF', 'ANSWER');
  end if;

  if not exists (select 1 from pg_type where typname = 'question_status') then
    create type public.question_status as enum ('WAITING', 'COMPLETED', 'ARCHIVED');
  end if;
end $$;

-- ─────────────────────────────────────────────────────────────
-- Tables
-- ─────────────────────────────────────────────────────────────

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null,
  email text not null,
  credit integer not null default 100,
  position public.position not null default 'NONE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.insights (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null default '',
  initial_thought text not null,
  views integer not null default 0,
  trashed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.insight_pieces (
  id bigint generated by default as identity primary key,
  insight_id bigint not null references public.insights(id) on delete cascade,
  content text not null,
  created_type public.created_type not null,
  created_at timestamptz not null default now()
);

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  color_code text,
  created_at timestamptz not null default now(),
  constraint tags_user_id_name_key unique (user_id, name)
);

create table if not exists public.insight_tags (
  insight_id bigint not null references public.insights(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  primary key (insight_id, tag_id)
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  insight_id bigint not null references public.insights(id) on delete cascade,
  content text not null,
  status public.question_status not null default 'WAITING',
  version bigint not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.answers (
  id bigint generated by default as identity primary key,
  question_id bigint not null unique references public.questions(id) on delete cascade,
  content text not null,
  is_converted boolean not null default false,
  created_at timestamptz not null default now()
);

-- Optional tables from the previous Spring backend. Keep for later AI features/history.
create table if not exists public.insight_candidates (
  id bigint generated by default as identity primary key,
  insight_piece_id bigint not null references public.insight_pieces(id) on delete cascade,
  content text not null,
  version bigint not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.answer_insight_promotions (
  id bigint generated by default as identity primary key,
  answer_id bigint not null unique references public.answers(id) on delete cascade,
  insight_piece_id bigint not null unique references public.insight_pieces(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.links (
  id bigint generated by default as identity primary key,
  insight_id bigint not null references public.insights(id) on delete cascade,
  title text not null default '',
  content text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────
-- Indexes
-- ─────────────────────────────────────────────────────────────

create index if not exists idx_insights_user_id_created_at on public.insights(user_id, created_at desc);
create index if not exists idx_insights_user_id_trashed_at on public.insights(user_id, trashed_at);
create index if not exists idx_insight_pieces_insight_id_created_at on public.insight_pieces(insight_id, created_at asc);
create index if not exists idx_tags_user_id_name on public.tags(user_id, name);
create index if not exists idx_insight_tags_tag_id on public.insight_tags(tag_id);
create index if not exists idx_questions_insight_id_status_created_at on public.questions(insight_id, status, created_at desc);
create index if not exists idx_answers_question_id on public.answers(question_id);
create index if not exists idx_insight_candidates_piece_id_created_at on public.insight_candidates(insight_piece_id, created_at desc);
create index if not exists idx_links_insight_id on public.links(insight_id);

-- ─────────────────────────────────────────────────────────────
-- Timestamp helpers
-- ─────────────────────────────────────────────────────────────

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.prevent_client_credit_update()
returns trigger
language plpgsql
as $$
begin
  if auth.uid() is not null and new.credit is distinct from old.credit then
    raise exception 'profiles.credit cannot be changed by client requests';
  end if;

  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists prevent_client_credit_update on public.profiles;
create trigger prevent_client_credit_update
before update on public.profiles
for each row execute function public.prevent_client_credit_update();

drop trigger if exists set_insights_updated_at on public.insights;
create trigger set_insights_updated_at
before update on public.insights
for each row execute function public.set_updated_at();

drop trigger if exists set_links_updated_at on public.links;
create trigger set_links_updated_at
before update on public.links
for each row execute function public.set_updated_at();

-- ─────────────────────────────────────────────────────────────
-- Auth user → profile auto creation
-- ─────────────────────────────────────────────────────────────

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, nickname, email, credit, position)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1), 'User'),
    coalesce(new.email, ''),
    100,
    'NONE'
  )
  on conflict (id) do update set
    nickname = excluded.nickname,
    email = excluded.email;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- ─────────────────────────────────────────────────────────────
-- RLS enable
-- ─────────────────────────────────────────────────────────────

alter table public.profiles enable row level security;
alter table public.insights enable row level security;
alter table public.insight_pieces enable row level security;
alter table public.tags enable row level security;
alter table public.insight_tags enable row level security;
alter table public.questions enable row level security;
alter table public.answers enable row level security;
alter table public.insight_candidates enable row level security;
alter table public.answer_insight_promotions enable row level security;
alter table public.links enable row level security;

-- ─────────────────────────────────────────────────────────────
-- RLS policies
-- ─────────────────────────────────────────────────────────────

-- profiles
drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles
for select using (id = auth.uid());

drop policy if exists profiles_insert_own on public.profiles;
create policy profiles_insert_own on public.profiles
for insert with check (id = auth.uid() and credit = 100);

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles
for update using (id = auth.uid()) with check (id = auth.uid());

-- insights
drop policy if exists insights_select_own on public.insights;
create policy insights_select_own on public.insights
for select using (user_id = auth.uid());

drop policy if exists insights_insert_own on public.insights;
create policy insights_insert_own on public.insights
for insert with check (user_id = auth.uid());

drop policy if exists insights_update_own on public.insights;
create policy insights_update_own on public.insights
for update using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists insights_delete_own on public.insights;
create policy insights_delete_own on public.insights
for delete using (user_id = auth.uid());

-- insight_pieces
drop policy if exists insight_pieces_select_own on public.insight_pieces;
create policy insight_pieces_select_own on public.insight_pieces
for select using (
  exists (
    select 1 from public.insights i
    where i.id = insight_pieces.insight_id and i.user_id = auth.uid()
  )
);

drop policy if exists insight_pieces_insert_own on public.insight_pieces;
create policy insight_pieces_insert_own on public.insight_pieces
for insert with check (
  exists (
    select 1 from public.insights i
    where i.id = insight_pieces.insight_id and i.user_id = auth.uid()
  )
);

drop policy if exists insight_pieces_update_own on public.insight_pieces;
create policy insight_pieces_update_own on public.insight_pieces
for update using (
  exists (
    select 1 from public.insights i
    where i.id = insight_pieces.insight_id and i.user_id = auth.uid()
  )
) with check (
  exists (
    select 1 from public.insights i
    where i.id = insight_pieces.insight_id and i.user_id = auth.uid()
  )
);

drop policy if exists insight_pieces_delete_own on public.insight_pieces;
create policy insight_pieces_delete_own on public.insight_pieces
for delete using (
  exists (
    select 1 from public.insights i
    where i.id = insight_pieces.insight_id and i.user_id = auth.uid()
  )
);

-- tags
drop policy if exists tags_select_own on public.tags;
create policy tags_select_own on public.tags
for select using (user_id = auth.uid());

drop policy if exists tags_insert_own on public.tags;
create policy tags_insert_own on public.tags
for insert with check (user_id = auth.uid());

drop policy if exists tags_update_own on public.tags;
create policy tags_update_own on public.tags
for update using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists tags_delete_own on public.tags;
create policy tags_delete_own on public.tags
for delete using (user_id = auth.uid());

-- insight_tags
drop policy if exists insight_tags_select_own on public.insight_tags;
create policy insight_tags_select_own on public.insight_tags
for select using (
  exists (
    select 1
    from public.insights i
    join public.tags t on t.id = insight_tags.tag_id
    where i.id = insight_tags.insight_id
      and i.user_id = auth.uid()
      and t.user_id = auth.uid()
  )
);

drop policy if exists insight_tags_insert_own on public.insight_tags;
create policy insight_tags_insert_own on public.insight_tags
for insert with check (
  exists (
    select 1
    from public.insights i
    join public.tags t on t.id = insight_tags.tag_id
    where i.id = insight_tags.insight_id
      and i.user_id = auth.uid()
      and t.user_id = auth.uid()
  )
);

drop policy if exists insight_tags_delete_own on public.insight_tags;
create policy insight_tags_delete_own on public.insight_tags
for delete using (
  exists (
    select 1
    from public.insights i
    join public.tags t on t.id = insight_tags.tag_id
    where i.id = insight_tags.insight_id
      and i.user_id = auth.uid()
      and t.user_id = auth.uid()
  )
);

-- questions
drop policy if exists questions_select_own on public.questions;
create policy questions_select_own on public.questions
for select using (
  exists (
    select 1 from public.insights i
    where i.id = questions.insight_id and i.user_id = auth.uid()
  )
);

drop policy if exists questions_insert_own on public.questions;
create policy questions_insert_own on public.questions
for insert with check (
  exists (
    select 1 from public.insights i
    where i.id = questions.insight_id and i.user_id = auth.uid()
  )
);

drop policy if exists questions_update_own on public.questions;
create policy questions_update_own on public.questions
for update using (
  exists (
    select 1 from public.insights i
    where i.id = questions.insight_id and i.user_id = auth.uid()
  )
) with check (
  exists (
    select 1 from public.insights i
    where i.id = questions.insight_id and i.user_id = auth.uid()
  )
);

drop policy if exists questions_delete_own on public.questions;
create policy questions_delete_own on public.questions
for delete using (
  exists (
    select 1 from public.insights i
    where i.id = questions.insight_id and i.user_id = auth.uid()
  )
);

-- answers
drop policy if exists answers_select_own on public.answers;
create policy answers_select_own on public.answers
for select using (
  exists (
    select 1
    from public.questions q
    join public.insights i on i.id = q.insight_id
    where q.id = answers.question_id and i.user_id = auth.uid()
  )
);

drop policy if exists answers_insert_own on public.answers;
create policy answers_insert_own on public.answers
for insert with check (
  exists (
    select 1
    from public.questions q
    join public.insights i on i.id = q.insight_id
    where q.id = answers.question_id and i.user_id = auth.uid()
  )
);

drop policy if exists answers_update_own on public.answers;
create policy answers_update_own on public.answers
for update using (
  exists (
    select 1
    from public.questions q
    join public.insights i on i.id = q.insight_id
    where q.id = answers.question_id and i.user_id = auth.uid()
  )
) with check (
  exists (
    select 1
    from public.questions q
    join public.insights i on i.id = q.insight_id
    where q.id = answers.question_id and i.user_id = auth.uid()
  )
);

drop policy if exists answers_delete_own on public.answers;
create policy answers_delete_own on public.answers
for delete using (
  exists (
    select 1
    from public.questions q
    join public.insights i on i.id = q.insight_id
    where q.id = answers.question_id and i.user_id = auth.uid()
  )
);

-- insight_candidates
drop policy if exists insight_candidates_select_own on public.insight_candidates;
create policy insight_candidates_select_own on public.insight_candidates
for select using (
  exists (
    select 1
    from public.insight_pieces p
    join public.insights i on i.id = p.insight_id
    where p.id = insight_candidates.insight_piece_id and i.user_id = auth.uid()
  )
);

drop policy if exists insight_candidates_insert_own on public.insight_candidates;
create policy insight_candidates_insert_own on public.insight_candidates
for insert with check (
  exists (
    select 1
    from public.insight_pieces p
    join public.insights i on i.id = p.insight_id
    where p.id = insight_candidates.insight_piece_id and i.user_id = auth.uid()
  )
);

-- answer_insight_promotions
drop policy if exists answer_insight_promotions_select_own on public.answer_insight_promotions;
create policy answer_insight_promotions_select_own on public.answer_insight_promotions
for select using (
  exists (
    select 1
    from public.answers a
    join public.questions q on q.id = a.question_id
    join public.insights i on i.id = q.insight_id
    where a.id = answer_insight_promotions.answer_id and i.user_id = auth.uid()
  )
);

drop policy if exists answer_insight_promotions_insert_own on public.answer_insight_promotions;
create policy answer_insight_promotions_insert_own on public.answer_insight_promotions
for insert with check (
  exists (
    select 1
    from public.answers a
    join public.questions q on q.id = a.question_id
    join public.insights i on i.id = q.insight_id
    where a.id = answer_insight_promotions.answer_id and i.user_id = auth.uid()
  )
);

-- links
drop policy if exists links_select_own on public.links;
create policy links_select_own on public.links
for select using (
  exists (
    select 1 from public.insights i
    where i.id = links.insight_id and i.user_id = auth.uid()
  )
);

drop policy if exists links_insert_own on public.links;
create policy links_insert_own on public.links
for insert with check (
  exists (
    select 1 from public.insights i
    where i.id = links.insight_id and i.user_id = auth.uid()
  )
);

drop policy if exists links_update_own on public.links;
create policy links_update_own on public.links
for update using (
  exists (
    select 1 from public.insights i
    where i.id = links.insight_id and i.user_id = auth.uid()
  )
) with check (
  exists (
    select 1 from public.insights i
    where i.id = links.insight_id and i.user_id = auth.uid()
  )
);

drop policy if exists links_delete_own on public.links;
create policy links_delete_own on public.links
for delete using (
  exists (
    select 1 from public.insights i
    where i.id = links.insight_id and i.user_id = auth.uid()
  )
);
